openapi: 3.0.3
info:
  title: CoreMs Communication Service API
  description: |
    The Communication Service API allows users to send messages of various types, such as SMS, email, and Slack. It provides endpoints to send message, retrieve messages by ID, and fetch a list of messages based on various parameters.
    
    Authentication is required to access the API endpoints. The API expects a Bearer JWT token in the Authorization header for authentication.
  version: 1.0.0
servers:
  - url: http://localhost
tags:
  - name: AdminMessages
    description: Operations related to sending messages for admins
  - name: UserMessages
    description: Operations related to sending messages for users

# common error responses convenience anchor (references common API responses)
x-common-error-responses: &common-error-responses
  '400':
    $ref: '.gen/common-api.yaml#/components/responses/ValidationError'
  '401':
    $ref: '.gen/common-api.yaml#/components/responses/UnauthorizedError'
  '403':
    $ref: '.gen/common-api.yaml#/components/responses/ForbiddenError'
  '404':
    $ref: '.gen/common-api.yaml#/components/responses/NotFoundError'
  '500':
    $ref: '.gen/common-api.yaml#/components/responses/InternalServerError'

# Require bearer auth for all operations by default
security:
  - bearerAuth: []

paths:
  /api/admin/messages:
    get:
      tags:
        - AdminMessages
      summary: Get a list of messages (admin)
      description: Retrieve a paginated list of messages. Admins may filter by userId, type and other filters.
      operationId: getAdminMessages
      parameters:
        - $ref: '.gen/common-api.yaml#/components/parameters/page'
        - $ref: '.gen/common-api.yaml#/components/parameters/pageSize'
        - $ref: '.gen/common-api.yaml#/components/parameters/sort'
        - $ref: '.gen/common-api.yaml#/components/parameters/search'
        - $ref: '.gen/common-api.yaml#/components/parameters/filter'
        - name: userId
          in: query
          required: false
          description: Filter messages by user id
          schema:
            type: string
      responses:
        '200':
          description: Messages retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetMessagesForUser'
        <<: *common-error-responses

    post:
      tags:
        - AdminMessages
      summary: Send a message on behalf of a user (admin)
      description: Send a message (sms, email, slack) on behalf of the specified user. The request body MUST include userId when sending for another user.
      operationId: sendAdminMessage
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MessageRequest'
      responses:
        '201':
          description: Message accepted for processing
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageResponse'
        <<: *common-error-responses

  /api/messages:
    get:
      tags:
        - UserMessages
      summary: Get messages for the authenticated user
      description: Retrieve a paginated list of messages that belong to the authenticated user. Use query parameters for paging, sorting and filtering.
      operationId: getMyMessages
      parameters:
        - $ref: '.gen/common-api.yaml#/components/parameters/page'
        - $ref: '.gen/common-api.yaml#/components/parameters/pageSize'
        - $ref: '.gen/common-api.yaml#/components/parameters/sort'
        - $ref: '.gen/common-api.yaml#/components/parameters/search'
        - $ref: '.gen/common-api.yaml#/components/parameters/filter'
        - $ref: '#/components/parameters/TypeParameter'
      responses:
        '200':
          description: Messages retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetMessagesForUser'
        <<: *common-error-responses

    post:
      tags:
        - UserMessages
      summary: Send a message for the authenticated user
      description: Send a message on behalf of the authenticated user. The server will associate the message with the authenticated user; userId in the payload is optional and ignored for non-admins.
      operationId: sendMyMessage
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MessageRequest'
      responses:
        '201':
          description: Message accepted for processing
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageResponse'
        <<: *common-error-responses

components:
  schemas:
    MessageRequest:
      type: object
      required:
        - type
      properties:
        userId:
          type: string
          description: For admin only to specify user on whose behalf the message is sent
        type:
          type: string
          enum:
            - sms
            - slack
            - email
      discriminator:
        propertyName: type
        mapping:
          sms: "#/components/schemas/SmsRequest"
          email: "#/components/schemas/EmailRequest"
          slack: "#/components/schemas/SlackRequest"

    SmsRequest:
      type: object
      allOf:
        - $ref: "#/components/schemas/MessageRequest"
        - type: object
          required:
            - phoneNumber
            - message
          properties:
            phoneNumber:
              type: string
              pattern: '^\+\d{1,20}$'
              description: Recipient phone number in E.164 format (e.g. +15551234567)
            message:
              type: string
              minLength: 1
              maxLength: 1600
              description: >
                SMS text body. Max 1600 chars accepted (concatenated messages).
                Single-part SMS typical max: 160 chars (GSM-7) or 70 (UCS-2).

    EmailRequest:
      type: object
      allOf:
        - $ref: "#/components/schemas/MessageRequest"
        - type: object
          required:
            - emailType
            - subject
            - sender
            - recipient
            - body
          properties:
            emailType:
              type: string
              default: TXT
              enum:
                - TXT
                - HTML
              description: Email type HTML or TXT
            cc:
              type: array
              items:
                type: string
                format: email
              example:
                - john@example.com
                - jane@example.org
              description: CC recipient email addresses
            bcc:
              type: array
              items:
                type: string
                format: email
              example:
                - hidden@example.com
              description: BCC recipient email addresses
            sender:
              type: string
              format: email
              maxLength: 254
              description: Sender's email address
            senderName:
              type: string
              maxLength: 100
              description: Sender's name
            subject:
              type: string
              minLength: 1
              maxLength: 255
              description: Subject of the email message
            recipient:
              type: string
              format: email
              maxLength: 254
              description: Recipient's address
            body:
              type: string
              minLength: 1
              maxLength: 10000
              description: Body content of the message

    SlackRequest:
      type: object
      allOf:
        - $ref: "#/components/schemas/MessageRequest"
        - type: object
          required:
            - channel
            - message
          properties:
            channel:
              type: string
              pattern: "^(#|@).+"
              description: Slack channel (channel name starting with # or user mention starting with @)
            message:
              type: string
              minLength: 1
              maxLength: 4000
              description: Slack message

    MessageResponse:
      type: object
      properties:
        id:
          type: string
          description: ID of the message
        type:
          type: string
          description: Type of the message (sms, email, slack)
        status:
          type: string
          description: Status of the message
        createdAt:
          type: string
          format: date-time
          description: Creation date of the message
        data:
          $ref: '#/components/schemas/MessageRequest'

    GetMessagesForUser:
      type: object
      properties:
        total:
          type: integer
        page:
          type: integer
        pageSize:
          type: integer
        items:
          type: array
          items:
            $ref: '#/components/schemas/MessageResponse'

  parameters:
    TypeParameter:
      name: type
      in: query
      required: false
      description: Type of the message (sms, email, slack)
      schema:
        type: string
        enum:
          - sms
          - email
          - slack

    UserIdParameter:
      name: userId
      in: query
      required: false
      description: Filter messages by user id
      schema:
        type: string
        pattern: "^[0-9a-fA-F\\-]{36}$"
