openapi: 3.0.3
info:
  title: CoreMs Communication Service API
  description: |
    The Communication Service API allows users to send messages of various types, such as SMS, email, and Slack. It provides endpoints to send message, retrieve messages by ID, and fetch a list of messages based on various parameters.
    
    Authentication is required to access the API endpoints. The API expects a Bearer JWT token in the Authorization header for authentication.
  version: 1.0.0
servers:
  - url: http://localhost
tags:
  - name: Message
    description: Operations related to sending messages

# common error responses convenience anchor (references common API responses)
x-common-error-responses: &common-error-responses
  '400':
    $ref: '.gen/common-api.yaml#/components/responses/ValidationError'
  '401':
    $ref: '.gen/common-api.yaml#/components/responses/UnauthorizedError'
  '404':
    $ref: '.gen/common-api.yaml#/components/responses/NotFoundError'
  '500':
    $ref: '.gen/common-api.yaml#/components/responses/InternalServerError'

# Require bearer auth for all operations by default
security:
  - bearerAuth: []

paths:
  /api/v1/users/{userId}/messages:
    parameters:
      - name: userId
        in: path
        required: true
        description: User ID to scope messages to
        schema:
          type: string
    get:
      tags:
        - Message
      summary: Get a list of messages for a user
      description: Retrieve a list of messages for the given user. Supports optional filtering by type.
      operationId: getMessagesForUser
      parameters:
        - $ref: '#/components/parameters/TypeParameter'
        - $ref: '.gen/common-api.yaml#/components/parameters/page'
        - $ref: '.gen/common-api.yaml#/components/parameters/pageSize'
        - $ref: '.gen/common-api.yaml#/components/parameters/sort'
        - $ref: '.gen/common-api.yaml#/components/parameters/search'
        - $ref: '.gen/common-api.yaml#/components/parameters/filter'
      responses:
        '200':
          description: Messages retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetMessagesForUser'
        <<: *common-error-responses

    post:
      tags:
        - Message
      summary: Send a message for a user
      description: Send a message of the specified type (sms, email, slack) on behalf of the given user.
      operationId: sendMessageForUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MessageRequest'
      responses:
        '201':
          description: Message accepted for processing
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageResponse'
        <<: *common-error-responses

  /api/v1/users/{userId}/messages/{messageId}:
    parameters:
      - name: userId
        in: path
        required: true
        schema:
          type: string
      - name: messageId
        in: path
        required: true
        schema:
          type: string
    get:
      tags:
        - Message
      summary: Get a message by id for a user
      description: Retrieve a single message by its id scoped to the given user.
      operationId: getMessageById
      responses:
        '200':
          description: Message retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageResponse'

components:
  schemas:
    MessageRequest:
      type: object
      required:
        - type
      properties:
        type:
          type: string
          enum:
            - sms
            - slack
            - email
      discriminator:
        propertyName: type
        mapping:
          sms: "#/components/schemas/SmsRequest"
          email: "#/components/schemas/EmailRequest"
          slack: "#/components/schemas/SlackRequest"

    SmsRequest:
      type: object
      allOf:
        - $ref: "#/components/schemas/MessageRequest"

    EmailRequest:
      type: object
      allOf:
        - $ref: "#/components/schemas/MessageRequest"
        - type: object
          required:
            - emailType
            - subject
            - sender
            - recipient
            - body
          properties:
            emailType:
              type: string
              default: TXT
              enum:
                - TXT
                - HTML
              description: Email type HTML or TXT
            cc:
              type: string
              description: Email addresses(comma separated) to include in CC
            bcc:
              type: string
              description: Email addresses(comma separated) to include in BCC
            sender:
              type: string
              description: Sender's email address
            senderName:
              type: string
              description: Sender's name
            subject:
              type: string
              description: Subject of the email message
            recipient:
              type: string
              description: Recipient's address
            body:
              type: string
              description: Body content of the message

    SlackRequest:
      type: object
      allOf:
        - $ref: "#/components/schemas/MessageRequest"
        - type: object
          required:
            - channel
            - message
          properties:
            channel:
              type: string
              description: Slack channel
            message:
              type: string
              description: Slack message

    MessageResponse:
      type: object
      properties:
        id:
          type: string
          description: ID of the message
        type:
          type: string
          description: Type of the message (sms, email, slack)
        status:
          type: string
          description: Status of the message
        createdAt:
          type: string
          format: date-time
          description: Creation date of the message
        data:
          $ref: '#/components/schemas/MessageRequest'

    GetMessagesForUser:
      type: object
      properties:
        total:
          type: integer
        page:
          type: integer
        pageSize:
          type: integer
        items:
          type: array
          items:
            $ref: '#/components/schemas/MessageResponse'

  parameters:
    TypeParameter:
      name: type
      in: query
      required: false
      description: Type of the message (sms, email, slack)
      schema:
        type: string
        enum:
          - sms
          - email
          - slack
