spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${GOOGLE_CLIENT_ID}
            clientSecret: ${GOOGLE_CLIENT_SECRET}
            redirectUri: '{baseUrl}/oauth2/callback/{registrationId}'
            scope: email, profile
          github:
            clientId: ${GITHUB_CLIENT_ID}
            clientSecret: ${GITHUB_CLIENT_SECRET}
            redirectUri: '{baseUrl}/oauth2/callback/{registrationId}'
            scope: user:email, read:user

    jwt:
      secretKey: ${AUTH_TOKEN_SECRET}
      expirationTimeInMS: 86400000 # a day
