openapi: 3.0.3
info:
  title: CoreMs Notification Service API
  description: |
    The Notification Service API allows users to send notifications of various types, such as SMS, email, and Slack. It provides endpoints to send notifications, retrieve notifications by ID, and fetch a list of notifications based on various parameters.
    
    Authentication is required to access the API endpoints. The API expects a Bearer JWT token in the Authorization header for authentication.
  version: 1.0.0
tags:
  - name: Notification
paths:
  /notifications/send:
    post:
      tags:
        - Notification
      summary: Send a notification
      description: Send a notification of the specified type (sms, email, slack)
      operationId: sendNotification
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Notification'
      responses:
        '200':
          description: Notification sent successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotificationResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorWrapper'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorWrapper'
      security:
        - bearerAuth: [ ]
  /notifications:
    get:
      tags:
        - Notification
      summary: Get a list of notifications
      description: Retrieve a list of notifications of the specified type (sms, email, slack)
      operationId: getNotificationStatusList
      parameters:
        - $ref: '#/components/parameters/TypeParameter'
        - $ref: '#/components/parameters/UserIDParameter'
        - $ref: '#/components/parameters/FromDateParameter'
        - $ref: '#/components/parameters/ToDateParameter'
      responses:
        '200':
          description: Notifications retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/NotificationResponse'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorWrapper'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorWrapper'
      security:
        - bearerAuth: [ ]
components:
  schemas:
    Notification:
      type: object
      required:
        - type
      properties:
        type:
          type: string
          enum:
            - sms
            - slack
            - email
      discriminator:
        propertyName: type
        mapping:
          sms: "#/components/schemas/SmsNotification"
          email: "#/components/schemas/EmailNotification"
          slack: "#/components/schemas/SlackNotification"
          # chat: "#/components/schemas/ChatNotification"

    SmsNotification:
      type: object
      allOf:
        - $ref: "#/components/schemas/Notification"

    EmailNotification:
      type: object
      allOf:
        - $ref: "#/components/schemas/Notification"
        - required:
            - emailType
            - subject
            - sender
            - recipient
            - body
        - properties:
            emailType:
              type: string
              default: TXT
              enum:
                - TXT
                - HTML
              description: Email type HTML or TXT
            cc:
              type: string
              description: Email addresses(comma separated) to include in CC
            bcc:
              type: string
              description: Email addresses(comma separated) to include in BCC
            sender:
              type: string
              description: Sender's email address
            senderName:
              type: string
              description: Sender's name
            subject:
              type: string
              description: Subject of the email notification
            recipient:
              type: string
              description: Recipient's address
            body:
              type: string
              description: Body content of the notification

    SlackNotification:
      type: object
      allOf:
        - $ref: "#/components/schemas/Notification"
        - required:
            - channel
            - message
        - properties:
            channel:
              type: string
              description: Slack channel
            message:
              type: string
              description: Slack message

    NotificationResponse:
      type: object
      properties:
        id:
          type: string
          description: ID of the notification
        type:
          type: string
          description: Type of the notification (sms, email, slack)
        status:
          type: string
          description: Status of the notification
        createdAt:
          type: string
          format: date-time
          description: Creation date of the notification
        data:
          $ref: '#/components/schemas/Notification'

    Error:
      type: object
      properties:
        ReasonCode:
          type: string
          description: Reason code for the error
        Description:
          type: string
          description: Description of the error
        Details:
          type: string
          description: Details of the error
      required:
        - ReasonCode
        - Description
        - Details

    ErrorList:
      type: array
      items:
        $ref: '#/components/schemas/Error'

    ErrorWrapper:
      type: object
      properties:
        errors:
          $ref: '#/components/schemas/ErrorList'
      required:
        - errors

  parameters:
    TypeParameter:
      name: type
      in: query
      required: false
      description: Type of the notification (sms, email, slack)
      schema:
        type: string
        enum:
          - sms
          - email
          - slack
    UserIDParameter:
      name: userId
      in: query
      required: false
      description: User ID to filter notifications
      schema:
        type: string
    FromDateParameter:
      name: fromDate
      in: query
      required: false
      description: Start date to filter notifications (inclusive)
      schema:
        type: string
        format: date-time
    ToDateParameter:
      name: toDate
      in: query
      required: false
      description: End date to filter notifications (inclusive)
      schema:
        type: string
        format: date-time
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
